grid_map_visualization:
  ros__parameters:
    grid_map_topic: /grid_map
    grid_map_visualizations: [elevation_cells, elevation_points, elevation_grid]
    elevation_cells:
      type: grid_cells
      params:
        layer: rob_cent_map
        lower_threshold: -inf
        upper_threshold: inf
    elevation_points:
      type: point_cloud
      params:
        layer: rob_cent_map
    elevation_grid:
      type: occupancy_grid
      params:
        layer: rob_cent_map
        data_min: 0.08
        data_max: -0.16
